POST http://localhost:3003/api/blog
Content-Type: application/json

{
    "title": "Wonderful life",
    "author": "Inderpal Singh",
    "url": "https://myblog.com/wonderful-life",
    "likes": "50"
}